name: Mocha Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build + Compile Extension
        run: npm run compile-web

      - name: Run Web Extension Tests
        run: xvfb-run npm test
        env:
          CI: true
